---
apiVersion: v1
kind: Service
metadata:
  name: external-vault
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8200
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-vault
addressType: IPv4
endpoints:
  - addresses:
    - 192.168.65.254
ports:
  - port: 8200
    protocol: TCP
    name: http
