---
apiVersion: v1
kind: Service
metadata:
  name: external-vault
  namespace: default
  labels:
    run: external-vault
spec:
  ports:
  - name: http
    port: 8200
    targetPort: http
  selector:
    run: external-vault
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-vault
  labels:
    kubernetes.io/service-name: external-vault
addressType: IPv4
endpoints:
  - addresses:
    - 0.0.0.1
ports: 
    - name: http
      port: 8200
